### ISSUE TITLE
Identity Server 3 compatibility test

### ISSUE THREAD

**Issue by tienw** [FormidableLabs/react-native-app-auth#28]
Hi All,

Thanks for guiding me in my previous post, I am able to configure it successfully and run this package on React Native. Here is the new issue I am facing

After I click the sign in button, the identity server login page pop up in webview, but it shows ""The client application is not known or is not authorized" so I copy to url and paste into the browser to see if all the query parameter are correct. Then I found that the "response type" is "code", once I switch to "token code", it works. But how can I do it in this module. I try to go through the document here but I could not find any way to change the response type. Any suggestion?

Thank you in advance.

**Comment by kadikraman** [comment]
AppAuth only supports the `code` response type and there is no plans to support hybrid flows.
> Hybrid (and implicit) negate the PKCE protection required by RFC 8252 so it's generally not recommended for native apps.

Relevant discussion: https://github.com/openid/AppAuth-iOS/issues/98

So I think this can probably be fixed with configuring the IdentityServer client and [changing the Flow](https://github.com/IdentityServer/IdentityServer3/blob/93bc6bc9b536146b9e3fa0bed21d77283d07f788/source/Core/Models/Enums.cs). Possibly `AuthorizationCodeWithProofKey` (which I think is the flow that supports PKCE)?

**Comment by sattaman** [comment]
I'm also wondering if ID Server 3 is supported. Using ID server 3, I've got it redirecting back to the app , but getting

> authorize error Error: invalid_client

with the following in the logs 

> 
> 2018-01-31 15:23:37.0259 Info Authorize request validation success
>  {
>   "ClientId": "stg-myapp",
>   "ClientName": "Staging myapp API",
>   "RedirectUri": "com.myapp:/oauthredirect",
>   "AllowedRedirectUris": [
>     "com.myapp:/oauthredirect"
>   ],
>   "SubjectId": "10159153140850220",
>   "ResponseType": "code",
>   "ResponseMode": "query",
>   "Flow": "AuthorizationCode",
>   "RequestedScopes": "openid offline_access",
>   "State": "TarsXZ2D2a6uN4fa49lDX-jz0EdacfnNwfEETtCE87s",
>   "SessionId": "ad5ed3168b437f3ba40cf442a63abaa8",
>   "Raw": {
>     "response_type": "code",
>     "code_challenge_method": "S256",
>     "scope": "openid offline_access",
>     "code_challenge": "ux9pt0-2R8GhvRU5FFS0JF6qBqxuLGlsOO25Mj5HybA",
>     "redirect_uri": "com.myapp:/oauthredirect",
>     "client_id": "stg-myapp",
>     "state": "TarsXZ2D2a6uN4fa49lDX-jz0EdacfnNwfEETtCE87s"
>   }
> } Thread= Session= App= Org= User= 
>  
> 2018-01-31 15:23:37.0415 Info Creating Authorization Code Flow response. Thread= Session= App= Org= User= 
>  
> 2018-01-31 15:23:37.0415 Info End authorize request Thread= Session= App= Org= User= 
>  
> 2018-01-31 15:23:37.0572 Info Redirecting to: com.myapp:/oauthredirect Thread= Session= App= Org= User= 
>  
> 2018-01-31 15:23:37.0884 Info Start token request Thread= Session= App= Org= User= 
>  
> 2018-01-31 15:23:37.1197 Info Parser found no secret Thread= Session= App= Org= User= 
>  
> 2018-01-31 15:23:37.1197 Info No client secret found Thread= Session= App= Org= User= 
>  
> 2018-01-31 15:23:37.1197 Info End token request Thread= Session= App= Org= User= 
>  
> 2018-01-31 15:23:37.1197 Info Returning error: invalid_client Thread= Session= App= Org= User= 
>  

With ID Server 4 it works fine.

**Comment by kadikraman** [comment]
@sattaman are you testing on iOS or Android?

**Comment by sattaman** [comment]
ios currently

**Comment by tienw** [comment]
tried AuthorizationCodeWithProofKey and still not working with id3..

**Comment by sattaman** [comment]
I've created a ID Server demo deployment 
https://site20180207034230.azurewebsites.net/

and still getting the same error `authorize error Error: invalid_client`

Using 

```
const auth = new AppAuth({
     issuer: ’https://site20180207034230.azurewebsites.net',
     clientId: ‘native.code’
});

const scopes = [‘openid’, ‘offline_access’];

auth.authorize(scopes)

```

Where the redirect is  `com.myapp:/oauthredirect`

**Comment by brockallen** [comment]
Check the IdentityServer logs to understand why you're getting the invalid client error. There must be some misconfiguration.

**Comment by kadikraman** [comment]
Thanks for hosting an example on Azure @sattaman - I tried to get one of the IS3 demos running locally, but I am on a Mac and not quite a pro at `.net` so thanks again 👍 

I think it's definitely an issue linking back into the native app. On iOS, the browser hides the error, but on Android you can see what it's trying to do:

![screen shot 2018-02-07 at 17 36 45](https://user-images.githubusercontent.com/6534400/35932365-5ee907a4-0c2f-11e8-963b-c9791227f106.png)

This is meant to deep link back into the native app and do the token exchange, but it's never getting there, because it's expecting to find a url scheme with `com.myapp:/oauthredirect` and not finding it.

**Comment by kadikraman** [comment]
@sattaman thanks so much for setting up the Azure website. I tried to run one of the IS3 demos locally before, but I'm not an `.net` pro and on a Mac so it was pretty tricky so this is much appreciated 👍

I can reproduce your error on both iOS and Android and the error is happening when trying to exchange the code for a JWT.

According to [the spec](https://tools.ietf.org/html/rfc6749#section-5.2), `invalid_client` means
```
Client authentication failed (e.g., unknown client, no
client authentication included, or unsupported
authentication method).  The authorization server MAY
return an HTTP 401 (Unauthorized) status code to indicate
which HTTP authentication schemes are supported.  If the
client attempted to authenticate via the "Authorization"
request header field, the authorization server MUST
respond with an HTTP 401 (Unauthorized) status code and
include the "WWW-Authenticate" response header field
matching the authentication scheme used by the client. 
```

**Comment by tienw** [comment]
@sattaman 

after I swtich from AuthorizationCodeWithProofKey to AuthorizationCode in id3 configuration

The invalid client error goes away. But now i am having issue return token to mobile app after signing in...

**Comment by sattaman** [comment]
```
Showing consent screen
Start token request
Start parsing Basic Authentication secret
Creating Authorization Code Flow response.
Start authorize request protocol validation
X.509 certificate not found.
Adding client "native.code" to client list cookie for subject "88421113"
Resuming from consent, restarting validation
No secret in post body found
Authorize request validation success
{
  "ClientId": "native.code",
  "ClientName": "Native Client (Code Flow with PKCE)",
  "RedirectUri": "com.myapp:/oauthredirect",
  "AllowedRedirectUris": [
    "com.myapp:/oauthredirect"
  ],
  "SubjectId": "88421113",
  "ResponseType": "code",
  "ResponseMode": "query",
  "Flow": "AuthorizationCodeWithProofKey",
  "RequestedScopes": "openid offline_access",
  "State": "cplNgFr-77LyHqqClDLFOLkx_kRSn3b00E27bEYw95w",
  "SessionId": "18b60951e585241650e644115ac33124",
  "CodeChallengeMethod": "S256",
  "Raw": {
    "response_type": "code",
    "code_challenge_method": "S256",
    "scope": "openid offline_access",
    "code_challenge": "RwPYiNZQF7OmmV9v7YGU6ZtoNNEWqIzy3_vOCF3DRtU",
    "redirect_uri": "com.myapp:/oauthredirect",
    "client_id": "native.code",
    "state": "cplNgFr-77LyHqqClDLFOLkx_kRSn3b00E27bEYw95w"
  }
}
Redirecting to: com.myapp:/oauthredirect
Start parsing for X.509 certificate
Start parsing for secret in post body
Start client validation
No client secret found
Returning error: invalid_client
Parser found no secret
End token request
```

**Comment by kadikraman** [comment]
Oh, interesting, so clearly it's not getting the client secret. Just looking at the [IS4 example setup](https://github.com/openid/AppAuth-iOS/blob/882191aaacd251039ee06e892616d147ff9b0c64/Examples/README-IdentityServer.md) for the parent library and they have set

```
RequireClientSecret = false
```

Is there a way to do the same on IS3 perhaps?

**Comment by sattaman** [comment]
Nice spot. I've found the following PR https://github.com/IdentityServer/IdentityServer3/pull/3653

Perhaps it will work with this, will give it a go.

**Comment by kadikraman** [comment]
Looks like it never got merged 😢 

It certainly makes sense now. We never implemented the auth request with client secrets, because IS4 and Google (the services we authenticated against) don't require them and you can't really hide secrets in a mobile app anyway as they have to be shipped with the bundle so it's not really "secret".

The parent libraries do provide that option though, e.g. [here](https://github.com/openid/AppAuth-iOS#authorizing-macos) so we could certainly wrap it.

**Comment by sattaman** [comment]
Also this https://github.com/IdentityServer/IdentityServer3/issues/2688

> Yes. IdentityServer simply always requires a client secret. Google works the same way, IIRC.
> 
> When I code native clients I use the value "not_a_secret" for the secret.

Ok sounds good :)

**Comment by kadikraman** [comment]
@tienw @sattaman we've just published a new version [v2.2.0](https://github.com/FormidableLabs/react-native-app-auth/releases/tag/v2.2.0) that will allow optionally passing in a client secret and thus will support IdentityServer 3.

We tested it against the example you uploaded @sattaman and it works. Instructions [here](https://github.com/FormidableLabs/react-native-app-auth#identity-server-3). Thanks so much for you help on this 😊
